export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const ALL_METRICS_DATA_RECEIVED = "ALL_METRICS_DATA_RECEIVED";
export const SELECTED_METRICS_RECEIVED = "SELECTED_METRICS_RECEIVED";
export const HISTORICAL_DATA_RECEIVED = "HISTORICAL_DATA_RECEIVED";
